### ISSUE TITLE
バックエンドプロジェクトの雛形

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#1]
NodejsのAPI雛形プロジェクトを作る。TypeScriptも。

エンドポイントを、ハンドラー（コントローラー）毎に振り分けて欲しいです。
main.tsでWebサーバー起動して、パス毎に処理を各ファイルに分配

- `/admin-line`
  - 管理LINEとのやりとり、admin_line.tsのadminLineHandler関数に処理を移譲
- `/user-line`
  - ユーザーLINEとのやりとり、user_line.tsのuserLineHandler関数に処理を移譲
- `/batch`
  - バッチ処理、月一でサイト再ビルドを発火、batch.tsのbatchHandler関数に処理を移譲

`/batch/ping`とリクエストすると`pong`を返すなど。

**Comment by Nekodigi** [comment]
以前要件をまとめたマインドマップのようなものを見せていただきましたが、実装する機能の一覧のようなものはありますか？
ひとまず、Cloud RunのデプロイとLINEの応答確認のみ行っています。

**Comment by tetsuyanh** [comment]
@Nekodigi 
マインドマップ共有フォルダに入れておきました。
https://drive.google.com/file/d/13-514bG2hIxX_SoekmVkXvq0drCrUllT/view?usp=share_link

タスクはProjectsの方に追加して、アサインしておきますね。
