### ISSUE TITLE
CloudRunへのAPIデプロイ（dev環境のみ）

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#11]
ゴール。
開発用の管理LINEが使えるようになる。（フォローしてから名前登録まで）

GCPプロジェクト：`thanks-web-dev`
発行された固定URLを、管理LINEのエンドポイントとして登録。

**Comment by Nekodigi** [comment]
@tetsuyanh 
thanks-web-devでCloud Runが有効になっていないかもしれません。
API [run.googleapis.com] not enabled on project [231229305548].
ERROR: (gcloud.run.deploy) User [ndeji69@gmail.com] does not have permission to access projects instance [thanks-web-dev]

**Comment by tetsuyanh** [comment]
@Nekodigi API有効にしました！

**Comment by Nekodigi** [comment]
@tetsuyanh 
Artifact Registry APIも必要みたいです。設定の程よろしくお願いします。
https://cloud.google.com/run/docs/quickstarts/build-and-deploy/deploy-nodejs-service?hl=ja

**Comment by tetsuyanh** [comment]
@Nekodigi 何度もすいません。。Artifact Registry APIも有効にしました！

**Comment by Nekodigi** [comment]
@tetsuyanh 
またすみません。Cloud Build APIも必要みたいです…
おそらくこれですべてだと思いますが、一度試してみたほうが良いかもしれません。
ERROR: (gcloud.run.deploy) PERMISSION_DENIED: Cloud Build API has not been used in project 231229305548 before or it is disabled.

**Comment by tetsuyanh** [comment]
@Nekodigi 
Cloud Build APIを有効にして、デプロイしました。
` gcloud beta run deploy thanks-web-backend-dev --source .`
regionは無難に東京を選択。 ` [3] asia-northeast1`

デプロイはできました。
環境変数がなくて、コンテナ起動に失敗してるので、設定してみてくださいー。
https://console.cloud.google.com/run?hl=ja&project=thanks-web-dev

**Comment by Nekodigi** [comment]
無事こちらでもDeploy出来ました。環境変数をセットし無事に動作も確認しました。
Managerを管理アプリ、Recipientを投稿アプリのアカウントに設定しました。
デモURLはこちらです。
https://lin.ee/gSRRbKD
