### ISSUE TITLE
CroudRunへの自動デプロイ（dev環境のみ）

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#12]
これが前提 #11 
GithubActionsで、こういう風にしたいです。

- developブランチへの（Github上でdevelop向きのPRを）マージ
  - 開発環境へのデプロイ（firebaseで作ったプロジェクト`thanks-web-dev`）

本番はあとでやる。

**Comment by Nekodigi** [comment]
権限の問題で、Github Actionの環境変数の登録やWorkload Identity Poolの設定ができそうにないです。
現在2つの記事を確認しましたが、あまりyamlの設定に慣れていないこともあるので、自動デプロイの設定を代わりに行っていただけますでしょうか？
最新記事
https://zenn.dev/harusame0616/articles/1caea25fbf60ab
簡易的な実現方法
https://zenn.dev/konnyaku256/articles/auto-deploy-with-cloudrun-and-githubactions

**Comment by tetsuyanh** [comment]
@Nekodigi 
すいません、ちょっと忙しく手が出せそうに無いので、権限渡すのでお試しください。
まだ開発環境だし、色々試してOKです。
Github組織アカウントのOwnerに加えました。
GCP`thanks-web-dev`のオーナーに招待しました。（招待メールが入ってるはず）→ndeji69@gmail.com

ちなみに私は、ローカル（認証は通った後）からCloudRunへデプロイする際はこのコマンドを叩いていて、
コンテナイメージの生成からデプロイまで一発でやってくれます。
`gcloud beta run deploy {CloudRunサービス名} --source .`
（挙げてくれた2つ目の記事で少し触れてますね、Actionsからできないかもだけど・・）

**Comment by Nekodigi** [comment]
gcloudのコマンドに慣れておらず、苦戦しています。
二番目の記事では
`Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/_actions/GoogleCloudPlatform/github-actions/main/setup-gcloud'. Did you forget to run actions/checkout before running your local action?`
というエラーが出て。
最新記事では、サービス アカウントの権限借用の設定以降のコマンドがうまく動かせません。
Cloud Buildを使ったContinuous Deployというものがあるようですが、これでも今回の要件を満たせそうでしょうか？
そちらも試しているものの、`bash: src/main.ts: Permission denied`が出ます。
https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build#setup-cd
ちょっと自力での実装が厳しそうなので、後日手助けしていただけるとありがたいです。
