### ISSUE TITLE
受給側LINEのユーザー登録まわり

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#15]
あらかじめ、FireStoreの管理コンソールで「食糧受給団体（ユーザーの上位概念）」は登録しておく。
（実際の運用でも、ここは運営側が手動で登録する想定）

受給側LINEの登録フローの実装（投稿できるまでの状態）。

- フォロー時
  - アカウント有りかつ登録済み（enable===true）
    - 「おかえりなさい」の旨
  - アカウント無し（不足している情報を埋めていく）
    - 名前無し→「お名前を教えてください。（サイトには公開されません）」
    - 食糧受給団体ID無し→「フードバンク山口から払い出された団体IDを入力してください。」食糧受給団体ID 
      - 団体紐付け失敗：「団体IDが見つかりません。もう一度入力をお願いします。」
      - 団体紐付け完了：「登録が完了しました。ありがとうございました。投稿することができます。」
-  アンフォロー時
    - enable->falseにする

スキーマはこちら。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema#recipientmembers

**Comment by tetsuyanh** [comment]
フォロー時に条件分岐しますが、そのあたりをテストしたいです。
先日のPRレビューでも言ったように、テスト時はDB接続せずユーザーの状態をモックで当てられるように。

**Comment by Nekodigi** [comment]
モックの書き方が良く分からず苦戦しています。
テストコードから実際のコードを呼び出さず、二重で書くのはよくないですよね…
参考になる物があれば教えていただきたいです。
https://jestjs.io/ja/docs/mock-functions

**Comment by Nekodigi** [comment]
分岐テストのテストコードを一つ書いてみました。
ただし、かなり冗長な感じがします。分岐自体かなり多くなると思うので、なるべくシンプルに書きたいのですが、モックを簡潔に書く方法はないでしょうか？
```javascript
jest.mock('../../lib/firestore/recipient', () => ({
  updateRecipient: jest.fn(),
  getRecipientByLineId: jest.fn(() => {
    return {
      id: 'r-0001',
      recipientGroupId: 'rg-0001',
      lineId: 'U2e895cd5524df946e924c9c5be624e61',
      name: '',
      status: '初期状態',
      enable: false,
      createdAt: new Date('December 15, 1990 01:23:00'),
    } as Recipient
  }),
}))

test('line recipient_line/recipient_line message', async () => {
  const event = {
    type: 'follow',
    source: { userId: 'Uada2abc97a874ae0a223eb4ddc72691b' },
  } as any
  expect(await handleEvent(event)).toMatchObject([
    {
      type: 'text',
      text: '友だち追加ありがとうございます。\nこのアカウントでは、文章や画像をチャット送っていただくだけで記事投稿が出来ます。',
    },
    { text: 'まず、お名前を教えてください。（サイトには公開されません）', type: 'text' },
  ])
})
```

**Comment by tetsuyanh** [comment]
@Nekodigi 

受給者のstatusに応じて返答が変わるケースが多いと思うので、まずは
ステータスだけを変える受給者生成の関数はどうですかね？

```
const getRecipient = (status: RecipientStatus): Recipient => {
   return {
      id: 'r-0001',
      recipientGroupId: 'rg-0001',
      lineId: 'U2e895cd5524df946e924c9c5be624e61',
      name: '太郎',
      status: status,
      enable: false,
      createdAt: new Date('December 15, 1990 01:23:00'),
    }
}

jest.mock('../../lib/firestore/recipient', () => ({
  updateRecipient: jest.fn(),
  getRecipientByLineId: jest.fn(() => return getRecipient(RECIPIENT_STATUS_NONE)),
})
```

**Comment by tetsuyanh** [comment]
返答のコピペも、ちょっと辛そうですね。。
この層が、中間層なので一番めんどくさいかもです。1,2つケースをやって、あとはToDo明記でもいいですよ。

**Comment by Nekodigi** [comment]
フォロー時の流れについて、テストを書いてみました。
暫定ですが、この書き方で良いかどうか確認お願いします。

**Comment by tetsuyanh** [comment]
@Nekodigi 良いと思います。

ここは具体的な日本語の方がいいかなと思います。
`it('!name_!id'`

test実行時にこんな感じで並ぶと、コケた場所やケースがわかりやすいです。
「フォロー：名前入力から再開」
「フォロー：団体ID入力から再開」
「フォロー：即復帰」

あと、実装の話はPRの方で一緒にやりましょう。今分散してて、ちょっと辛いです。
こちらはissueなので、実装前の課題を精査する話になります。
