### ISSUE TITLE
受給側LINEの投稿まわり

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#18]
- 「投稿」と話しかけると、投稿フロスタート
- 以後はプロトタイプと同じように、会話を進めて投稿素材を収集していく。

スキーマとステータスはWikiに記載。
ざっくりなので、随時提案してください。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema#posts

送信確認は、FlexMessagede作るのどうでしょうか。（私が開発していたアプリのように）
https://developers.line.biz/ja/docs/messaging-api/using-flex-messages/

レビューを依頼するステータスまでやる。
以後の管理者LINE側の許可は別issueで進める。

**Comment by tetsuyanh** [comment]
@Nekodigi 次のタスクです。よろしくお願いします。

**Comment by Nekodigi** [comment]
各ステップごとに確認メッセージを入れたほうが良いですよね。

**Comment by tetsuyanh** [comment]
@Nekodigi そうですね。
ITに詳しくない方が使うので、毎回メッセージで丁寧に説明や応答をしてあげましょう。

**Comment by Nekodigi** [comment]
画像複数入力の終了の判定は、ユーザーからのメッセージ入力、毎回終了確認ボタンを送るなどを考えています。今のところ何らかの文字入力とトリガとして、画像追加を終了するかの確認メッセージを送ろうと思っていますが、もっと良い方法はありますか？
また、記事投稿のトリガーは文字列とQuick ReplyとTemplate Messageとリッチメニューのどれが良いでしょうか？

**Comment by Nekodigi** [comment]
また、recipientからpostに向かう紐付けがあったほうが良いかなと思います。

**Comment by tetsuyanh** [comment]
> recipientからpostに向かう紐付け

posts側がrecipientGroupやrecipientへの紐付けを持っています。

どのようなユースケースを想定していますか？
recipentはマスタテーブルに近い感じで、都度更新は避けておきたいなと。

マスタとトランザクションの概要。
https://zenn.dev/dove/articles/c5672dda4c268e

**Comment by tetsuyanh** [comment]
> また、記事投稿のトリガーは文字列とQuick ReplyとTemplate Messageとリッチメニューのどれが良いでしょうか？

私の過去実績では、何か話しかけたらクイックリプライで選択肢を聞きトリガーとしていました。
「記事投稿」「記事削除」「何もしない」
「記事投稿」を選んだ時に、「記事投稿」というメッセージをしたようにできますよね。
なので、アイドル状態時に「記事投稿」というテキスト（文字れる）を受け取ったら、記事投稿モードへの状態管理に移行する。
（この仕様を分かってて、最初から「記事投稿」と手打ちしてもらってもいい）

リッチメニューもありですね。大きくボタンっぽいものを配置できるので。
ただし、メニューの開閉の操作、テキスト入力との切り替え、など若干、使い勝手は懸念があります。
あと、メニュー絵素材やレイアウトの管理/変更の手間の運用コストも少しあがりますね。

いずれ、どちらも試す/やる、になるかもしれませんが、
一旦は、プログラマブルだけで完結できる前者がいいのではと考えています。

**Comment by Nekodigi** [comment]
recipientからポスト編集のメッセージが来たときは、post.where("recipientId", "==", recipient.id)のようにして対象postを探すという流れになるということですよね。
マスタの変更を極力さけ、トランザクション側がマスタへの参照を持っておくのが良いんですね。分かりました。

**Comment by tetsuyanh** [comment]
> 画像複数入力の終了の判定は、ユーザーからのメッセージ入力、毎回終了確認ボタンを送るなどを考えています。今のところ何らかの文字入力とトリガとして、画像追加を終了するかの確認メッセージを送ろうと思っていますが、もっと良い方法はありますか？

画像を受け付けるたびに、追加の画像があれば受け付ける旨のメッセージ、とクイックリプライの「画像完了」を出すのはどうしょうか？
上記同様に、「画像完了」の文字列を終了判定とします。

もし、違うテキストがきたら、再度同じことを繰り返し聞きます。
画像を投稿し続けるか、完了、の選択肢しかできない。
画像は最大3件とかにして、3件受け付けたら自動完了とか仕込んでおきましょうか。

**Comment by tetsuyanh** [comment]
> recipientからポスト編集のメッセージが来たとき

そうです。
recipientの状態確認して、作成途中であれば、recipientIdと作成途中ステータスの2つをキーにpostを引きます。


> マスタの変更を極力さけ、トランザクション側がマスタへの参照を持っておくのが良いんですね。

そういう棲み分けは良いDB設計の入り口です。
要件によっては、recipient->postという矢印もなきにしもあらずですが、
recipientPostとか中間テーブルを作るようなことも検討に入ってきます。

**Comment by Nekodigi** [comment]
各文章の文字数制限はどの程度が良いでしょうか？
とりあえず、投稿途中の中断は想定しない、Quick Replyが使えるAndroidやiOS向けを想定する仕様で進めますか。

**Comment by Nekodigi** [comment]
また、post関連の処理が長いのでreact,reactPostText,reactPostImageの二つに分離しました。
画像取得でclientが必要になり、使用頻度は多くないですが、handleEvent、reactを通して渡す必要が出てきます。それでも、clientはグローバル変数にせず、引数として受け渡すほうが良いですよね。
clientを必要とするコード↓
```Javascript
export const downloadImageById = async (client: Client, id: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    client.getMessageContent(id).then((stream) => {
      const content = []
      stream
        .on('data', (chunk) => {
          content.push(Buffer.from(chunk))
        })
        .on('error', reject)
        .on('end', () => {
          resolve(Buffer.concat(content))
        })
    })
  })
}

```

**Comment by Nekodigi** [comment]
data.publishedAtは作成時未定になりますが、この場合はnullを入れるのが妥当でしょうか?

**Comment by tetsuyanh** [comment]
@Nekodigi コードみて意見したいので、Commit＆Pushしてください。

> data.publishedAtは作成時未定になりますが、この場合はnullを入れるのが妥当でしょうか?

はい。定義をnullableにしておいて、初期値を設定しない（欠けていてもTypeScriptでエラーにならない）、でいいです。
