### ISSUE TITLE
投稿のレビューフローまわり

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#21]
# 仕様

- recipientが投稿完了する
   - managers全員に投稿内容確認のPush
   - 投稿者の最終確認はテキストのメッセージのみで、タイムラインを遡れって感じでしたけど、
   - 原田の案件のようにFlexMessage?でそれっぽい投稿カードを見せてとはどうでしょうか？

- managersの1人（早い物順）が許可（ボタン？）
   - postが投稿対象（作業中をオフ）
   - recipientに投稿が許可された旨のPush
   - managers全員に投稿が**誰（登録された名前）に**許可された旨のPush
   - （後で、Web更新もキックする）

- managersの1人（早い物順）が不許可（ボタン？）
   - postをステータスで論理削除（作業中をオフ）
   - recipientに投稿が不許可された旨のPush
   - managers全員に投稿が**誰に**不許可された旨のPush
   - ゆくゆくは不許可の理由を管理して訂正フローにしたいが、初期実装には入れない

# 実装提案

LINEのPush（client.pushMessage）送信する共用の口を設ける。
このようなI/Fが良さそう。（実装段階で判断してください）
```
Push(client, lineIds, messages)
```

管理側は複数管理者を想定してるので、このような呼び方になりそう。
```
Push(client, getManagers(...).map((m) => m.id), messages)
```
recipient側は、投稿者だけへのPushになりそう。
```
Push(client, [post.recipientId], messages)
```

**Comment by Nekodigi** [comment]
Flex Messageで確認メッセージを作成しています。
ただ、画像を3つ入れようとするとレイアウトが崩れてしまいます。見た目は悪いですが、このまま進めて大丈夫でしょうか？
<img width="983" alt="Screen Shot 2023-05-02 at 9 06 13" src="https://user-images.githubusercontent.com/38092328/235552708-300a2158-ea5a-4a48-8b1d-5948ef47a144.png">
ただいま方法を調べています。

**Comment by Nekodigi** [comment]
<img width="967" alt="Screen Shot 2023-05-02 at 12 00 33" src="https://user-images.githubusercontent.com/38092328/235570817-bbdae01b-5989-4f76-a74a-01724a9c0bfd.png">
修正できました。
これで大丈夫でしょうか？

**Comment by tetsuyanh** [comment]
@Nekodigi 
上津原くん、せっかく画像3つに対応してもらったのにすいません。。。
Slackで茄子川さんに画像は1枚で始めましょうと言いました。
なので、1枚のみで大丈夫です。

**Comment by tetsuyanh** [comment]
プレビュー（FlexMessage）＋確認（Confirm選択）の2つのメッセージで分けて聞くのが良いと思います。

**Comment by Nekodigi** [comment]
このコードですが、recipientIdはlineIdではないので、一度getRecipientByIdなどでrecipientを取得してlineIdを取得する形で実装しました。応答改善のためにpostにrecipientLineIdを追加した方がよければ追加します。
`Push(client, [post.recipientId], messages)`

**Comment by Nekodigi** [comment]
Postの記事投稿時にPushメッセージを送る際にrecipeint_lineにmanager側のclientを、記事承認時にはmanager_lineにrecipient側のclientを渡す可能性ができてきそうなのですが、これもglobalを使わずhandlerから渡した方が良いですか？
冗長にならない方法はないでしょうか？

**Comment by tetsuyanh** [comment]
@Nekodigi 

> このコードですが、recipientIdはlineIdではないので

そうでした。
「getRecipientByIdなどでrecipientを取得」→こちらでOKです。

> managerとrecipientの相互Client

それぞれの受け取りディレクトリやファイルの棲み分けを`handler`と命名して、
- manager_handler（フォルダ）
  - manager_handler.ts（ファイル）
- recipinet_handler（フォルダ）
  - recipient_handler.ts（ファイル）

上記の各個別のhandlerのコンストラクタに上位から2つのclientを渡しましょう。
- managerClient
- recipientClient

**Comment by tetsuyanh** [comment]
それぞれのロジックを司るhandlerが、2つのclient（伝え先）を保持しているのは自然と思います。
