### ISSUE TITLE
管理者の投稿削除フロー

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#27]
管理者が「待機」状態で、話しかけると。クイックリプライボタン表示。

・「記事削除」
　→「記事IDを入力してください」（記事削除のID入力待ちステータス）

　・記事ID（テキストメッセージ）
　　→記事があれば、データを物理削除して、その旨を返答（待機ステータスに戻す）
　　→記事がなければ、記事が存在しなかった旨を返答（待機ステータスに戻す）

・「何もしない」
　→（＝テキストメッセージのアクション）無視して何の応答もしない。

受給者が話しかけて「何もしない」を選ぶと再度「投稿作成」を聞かれて堂々巡りになってるので無視するよう修正希望）

**Comment by Nekodigi** [comment]
記事削除もログに記録した方が良いでしょうか？

**Comment by tetsuyanh** [comment]
@Nekodigi はいお願いします。
記事IDで削除すると経緯がすべて確認できますね。
