### ISSUE TITLE
Web更新のキックと関係者へのPush通知（開発環境のみ）

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#28]
私の湯田案件を参考にできます。
（徳山高専Teamは閲覧許可を与えています）

バックエンドが、管理者の投稿承認完了時（または削除完了時）にGithubActionsへHTTPリクエストします↓
https://github.com/thwoo-inc/yuda-fox-backend/blob/main/handler/line/event.go#L271

このリクエスト先は、フロント側で定義されたActionで、外部から叩ける状態になっています。
（認証に必要なトークン発行して渡します）
https://github.com/thwoo-inc/yuda-fox-dev/blob/staging/.github/workflows/firebase-deploy-staging.yml

上記Actionが成功した時に、後続処理として発火するActionもこのように記述して、ここからバックエンドAPI↓を叩いてます。
湯田案件にはヘッダーに何も認証入れてないので今回は入れたい。
https://github.com/thwoo-inc/yuda-fox-dev/blob/staging/.github/workflows/backend-notify-staging.yml

バックエンド側に新たなエンドポイント`/published`でこのリクエストを受けて、
今回公開された投稿の関係者（投稿者、管理者）に記事のURL付きでPush送信する。
postsスキーマに`approvedManagerId`を足しました。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema#posts
該当の投稿は、投稿ステータスが完了になっている、かつpublishedAtがnullのもので、
処理の最後にpublishedAtに日付をいれて保存する。

**Comment by tetsuyanh** [comment]
@Nekodigi 次のタスクです。

**Comment by Nekodigi** [comment]
フロント側も変更する必要がありますよね。
取り掛かってみます。

**Comment by Nekodigi** [comment]
ymlの実行はfrontend側で行う必要がありますよね。
取り掛かってみます。

**Comment by Nekodigi** [comment]
@tetsuyanh 
そろそろ取り掛かるので、secretの発行等よろしくお願いします。
yamlはfrontend側にpushするようになりますよね。

**Comment by Nekodigi** [comment]
frontendでexportを試してみたのですが、Imageコンポーネントを使ってるのでexportできないようです。
feature/auto-deployで作業しているので確認お願いします。
Error: Image Optimization using Next.js' default loader is not compatible with `next export`.

**Comment by Nekodigi** [comment]
@tetsuyanh 
フロントエンド側のyamlも試しに書いてみていますが、FirebaseのServiceAccountに必要な権限が付与されていない気がします。
Cloud Functions Developerが有効になっていないといけないのでしょうか？確認よろしくお願いします。
https://stackoverflow.com/questions/57384609/gcloud-functions-deploy-permission-denied-when-deploying-function-with-specifi
```
  Error: HTTP Error: 403, Permission 'cloudfunctions.functions.list' denied on 'projects/thanks-web-dev/locations/-/functions'
  [2023-06-22T13:53:09.138Z] Error Context: ***
    "body": ***
      "error": ***
        "code": 403,
        "message": "Permission 'cloudfunctions.functions.list' denied on 'projects/thanks-web-dev/locations/-/functions'",
        "status": "PERMISSION_DENIED"
      ***
    ***,
    "response": ***
      "statusCode": 403
    ***
  ***
```

**Comment by tetsuyanh** [comment]
@Nekodigi こちら巻き取ります。別のタスク振ります。
