### ISSUE TITLE
ts-nodeやホットリロードの検討

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#3]
これだといちいちビルドし直さないといけないですよね。
`"start": "node dist/main.js",`

ts-nodeでTypescriptを直接実行できるので検討ください。
https://qiita.com/mangano-ito/items/75e65071c9c482ddc335

もっというと、ホットリロードがあるといいですね。
ファイルを保存すると、サーバー再起動してくれるやつ。

**Comment by Nekodigi** [comment]
ts-nodeについては、ローカル環境で使っているのですが、Cloud Runではコマンドが見つかりませんというエラーが以前出ました。これは単にdependenciesの中に含まれていなかったからで、含めたら実行できるということですか？
ホットリロードはnodemonを使った方法について調べてみます。

**Comment by Nekodigi** [comment]
ts-node、nodemon、導入成功しました。
他のIssue とまとめて修正してブランチを上げようと思います。

**Comment by Nekodigi** [comment]
prettierも加えて導入しました。ルールはフロント側と統一しました。
