### ISSUE TITLE
拠点管理の追加

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#32]
管理者や受給団体が所属する上位概念「拠点（ステーション）」の管理を追加する。
投稿確認/許可の通知を拠点間で閉じることでLINEのPush回数を抑える、
いずれ拠点ごとの投稿ページを分けることができる、が主な目的です。

スキーマ変更差分。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema/_compare/fdafb55698ab11f51d4a832c7e95604d7bb9136d...9efb4bbbf43bfaddbd889772182e7a449008bb45

変更点。
- 管理LINE
  - 初回登録フローの「拠点ID入力」のステップを入れてください。（拠点IDは、事前に伝達される運用）
  - 受給者の「受給団体ID入力」に相当するものです。検索して紐付けまで行う。
  - Push通知の対象は同じ拠点IDとしてください。（対象者クエリに拠点IDの条件に加える→複合インデクス追加が必要）
- 投稿LINE
  - 初回登録フローの受給団体紐付けの際に、団体と同じ拠点IDを受給ユーザーに持たせて保存してください。
  - 投稿作成時に、受給者と同じ拠点IDを持たせてく保存してください。
  - Push通知の対象は同じ拠点IDとしてください。（対象者クエリに拠点IDの条件に加える→複合インデクス追加が必要）

その他、変更点が必要であれば適宜お願いします。

**Comment by tetsuyanh** [comment]
@Nekodigi こちらお願いします。

**Comment by Nekodigi** [comment]
複数の"等式"のクエリなので、複合インデックスは必要なさそうです。
