### ISSUE TITLE
受給者がLINE登録を進めると名前入力ができないことがある

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#37]
フォローした後に名前を入力しても受け付けてもらえない。

![Screenshot_20230902-091419](https://github.com/foodbank-ymg/thanks-web-backend/assets/1460298/ff1601b2-452d-419b-8717-a4793f15ffab)

Firestoreを見ると、ステータスが「初期状態」になっていた。本来は「名前入力」。
コードの手続き順自体は問題なさそうで、操作の間や通信環境に依るのか？？

まずは、再現性の確認から。

**Comment by Nekodigi** [comment]
@tetsuyanh 
ブロックと再フォロー、友達追加を試しましたが、こちらではその状況は発生しませんでした。
ただし、仮にフォローしたままユーザーのデータが消された場合、初期状態のユーザーが仮に作られ、報告していただいたようにそこで詰まってしまいます。
おそらく現状はブロックと再フォローを行なってもらえれば直りますが、createRecipientした後に、INPUT_NAMEの状態にしておくとユーザーが見つからなかった際、自然に初期化の流れを行えると思いますがどうでしょうか?
多くのケースを想定するなら、初期状態で、名前がない時は強制的にINPUT_NAMEにするのも良いと思います。
<img width="611" alt="Screen Shot 2023-09-03 at 21 17 19" src="https://github.com/foodbank-ymg/thanks-web-backend/assets/38092328/0e63f1e3-f628-4625-954a-7df03d4a5d0c">

**Comment by tetsuyanh** [comment]
@Nekodigi では、createRecipient時の初期値を `INPUT_NAME`にしましょう。
一瞬で終わる作業だけどPRください。
