### ISSUE TITLE
不許可した時のフィードバックを入力させて伝える

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#47]
## 現状
管理者に来た投稿確認で、「不許可」を選択すると、投稿フローはやり直しになるのはいいが、
不備や理由を別途（電話/メール）に関して、管理者から投稿者に伝える必要があるため、LINEで完結したい。

## 修正案
- 管理者が不許可を押す
  - 投稿の`rejectedManagerId``rejectedAt`（新設）を更新（これを排他条件に加えたい。他の管理者の意思決定が送られてきても無視）
  - 担当の管理者のステータス**「不許可理由入力」（定数新設）**に更新
  - 「不許可の理由を教えてください。投稿された方に伝えます。（例：画像に〇〇が写っています/企業名が誤っています）」と返答
- 管理者がテキストを送ってくる
  - **投稿者と投稿のリセットはこのタイミングになる**
  - テキストをpostの`feedback`に保存。管理者を「不許可理由入力」ステータス（新設）に更新
  - 管理者に「入力ありがとうございます。投稿された方に伝えました。改めて投稿をしてもらいます。」と返答
  - 投稿者に「${subject}」の投稿が拒否されました。理由は以下の通りです。（改行）${feedback}」（現状の「誰が」に相当する${name}は外しましょう）

スキーマ
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema#posts

**Comment by Nekodigi** [comment]
この文章は管理者全員に送るものですか？
`入力ありがとうございます。投稿された方に伝えました。改めて投稿をしてもらいます。`
approvedPostForManagerも変えたほうが良いでしょうか？

**Comment by tetsuyanh** [comment]
@Nekodigi 
いえ、これも不許可した`rejectedManagerId`のみに送信してください。
投稿と最初に関わった管理者だけで閉じたメッセージのやりとりにしましょう。

すいません、要件追加です↓

- 不許可されたこともスプレッドシートのログに残したいです。`feedback`の理由も込める形で。
  - 操作: `投稿不許可`
  - 操作対象: `${timestamp}_${subject}_${feedback}`
　
- 初回の管理者が許可/不許可を済ませた後に、管理者（初回管理者含む）が許可/不許可を押した場合に、
`既に管理者によって、{許可/不許可}されました。`というレスポンス

**Comment by Nekodigi** [comment]
@tetsuyanh 
以前のrejectedPostForManager, approvedPostForManagerは削除して以下の文章を送信するのではなく、以前のメッセージに加えて追加でこれらのメッセージを投稿するということでしょうか？
それとも、許可不許可を押して初めて既に決定されたこと知るシステムにするべきですか？
また、投稿者には（現状の「誰が」に相当する${name}は外しましょう）は伝えられておらず、誰が決定したのかはあくまで管理者メッセージのみに記入されていますが、管理者向けメッセージからも削除した方が良いでしょうか？
また、許可はログに残さなくて良いですか？

**Comment by tetsuyanh** [comment]
許可/不許可したことがすでに管理者間でPushされており、いずれかのレビューが完了した投稿に対する許可/不許可は無視される。このままの仕様でOK。
結論、不許可の理由を入力するフェーズと、不許可の理由をログに入れるのみ。
