### ISSUE TITLE
503でコンテナが一度落ちてしまう

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#53]
# 現象
投稿の不許可を2名の管理者で実行したところ、GCPのログでこのようなエラーが起きていた。
フローを実施としては問題なかった。

503のサーバーエラー発生。
![スクリーンショット 2023-11-18 8 00 23](https://github.com/foodbank-ymg/thanks-web-backend/assets/1460298/f9f5afe9-f407-4ab9-9619-1bf9b1cb0d16)

LINEのReplyで空メッセージをリクエストしているっぽい。
![スクリーンショット 2023-11-18 8 00 46](https://github.com/foodbank-ymg/thanks-web-backend/assets/1460298/6c78952c-3a10-4a84-b99f-3005c3719fc9)

詳細はGCPで↓
https://console.cloud.google.com/logs/query;cursorTimestamp=2023-11-17T22:51:39.264135Z;duration=PT1H?hl=ja&project=thanks-web-dev

# 再現方法

- 同じステーションに属する管理者を2つ用意する。
- そのステーションに属する受給者が投稿する
- その投稿確認に対して、管理者Aが「不許可」を押す。（理由入力モードになる）
- 同様に、管理者Bが「不許可」を押す。
- 管理者Aが理由を入力して送信する。（←時間的にここで発生していそう）

管理者が2名でなく1名でも発生する事象かもしれません。

**Comment by tetsuyanh** [comment]
@Nekodigi 
急ぎません。手が空いた時があれば、ちょっと調べて対処してみてください。

**Comment by tetsuyanh** [comment]
@Nekodigi これ着手お願いします。

**Comment by Nekodigi** [comment]
コンテナが落ちるのは問題ですね…
編入対策と、定期テスト対策もあって最近少し忙しいですが、時間が取れるタイミングがあればちょっとみてみます。

**Comment by tetsuyanh** [comment]
> コンテナが落ちるのは問題ですね…

お行儀が良くないね。。きちんとエラー処理を施して、Webアプリは落ちないようにしたい。できれば。

**Comment by Nekodigi** [comment]
rejectedManagerIdが上書きされるのが原因かと思ったんですが、コード的にはちゃんとブロックしてるはずです。
ダメな場合でも、エラーは捕捉しているはずなので、落ちるまでは行かないですね…
LINEの複数アカウント現時点で持っていないので、色々探ってみます。
`INPUT_REJECT_REASON: post not found`

**Comment by Nekodigi** [comment]
thanks-web-devではどのタイミングでそのエラーが出ていますか？本番環境のログはアクセスを持っていない気がします。
管理者Bは仕様上、そのタイミングで不許可を押せないはずですが、管理者Bにレスポンスはありましたか?
ちょっと条件を再現できないので、もう少し細かくエラーや発生箇所について確認したいです。

**Comment by tetsuyanh** [comment]
こちらで２端末使って、改めて再現やログを確認してみます。

**Comment by tetsuyanh** [comment]
@Nekodigi すいません、こちら再現しなかったので取り下げます。。
