### ISSUE TITLE
管理者LINEのfollow/unfollow時の管理

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-backend#6]
スキーマはこちらに定義してます。
https://github.com/foodbank-ymg/thanks-web-backend/wiki/Schema

 ## follow時
LINEIDでmanager取得（無ければ新規作成）
名前が入ってればenable→trueで完了
名前が空であれば名前を聞くフェーズに（ステータスを「名前入力」などにして、テキストメッセージ待ち）　
↓
名前入力できたらenable→trueで完了（ステータスも空に戻す）

## unfollow時
enable→falseで完了

firestoreのアクセスは`/lib`などのフォルダで分けてください。

`getManagerByLineId(lineId)`, `updateManager(manager)`などservice層を一段設けて欲しいです。
（updateManagerStatus, updateMangerEnableなど分けるべきかどうかは考えてみてください）

handlerはservice層を順次呼び出してレスポンスやエラーハンドリングだけにとどめる。

**Comment by Nekodigi** [comment]
timestampはDateではなくfirestore.Timestampのことでしょうか？

**Comment by Nekodigi** [comment]
ステータスは日本語文字列で管理するコードで進めています。
